1. Numpy 배열의 초기화

In [1]:
import numpy as np # numpy import 후 np로 약자 지정

범위 배열 생성

In [2]:
array0 = np.arange(4) # 0~3의 배열 생성
print("array0:",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: [0 1 2 3]
array0 size: 4
array0 dtype: int32


0으로 초기화한 배열 생성

In [3]:
array0 = np.zeros((4, 4), dtype=float) # 0으로 초기화한 float타입의 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array0 size: 16
array0 dtype: float64


1으로 초기화한 배열 생성

In [4]:
array0 = np.ones((4, 4), dtype=float) # 1으로 초기화한 float타입의 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array0 size: 16
array0 dtype: float64


랜덤한 값의 배열 생성

In [5]:
array0 = np.random.randint(0, 15, (4, 4)) # 0~15의 랜덤한 값을 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[ 4  8 12  0]
 [12  7  1  7]
 [ 6  8  5 12]
 [13  0  7 10]]
array0 size: 16
array0 dtype: int32


표준정규분포를 갖는 배열 생성

In [6]:
array0 = np.random.normal (0, 1, (4, 4)) # 평균이 0, 표준편차가 1인 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[-0.83594591 -1.20188311 -1.05320855 -0.18966937]
 [ 1.20181632 -0.91580694  0.81518602  0.07167718]
 [-0.01931001  1.67890992  0.2378247  -1.30471993]
 [-0.70168283  0.60769567 -1.87763958 -0.51274564]]
array0 size: 16
array0 dtype: float64
