In [1]:
import numpy as np # numpy import 후 np로 약자 지정

0~15의 원소를 4x4배열로 생성 후 10미만의 원소를 100으로 mask

In [5]:
array0 = np.arange(16).reshape(4, 4) # 0~15의 원소를 4x4배열로 생성
print("array0:\n",array0) # 생성한 배열 출력

array1 = array0 < 10 # array0에서 10미만의 원소를 Mask
print("array1:\n",array1) # Mask한 배열 출력

array0[array1] = 100 # array1의 True값을 array0에 100으로 Mask
print("Mask100: \n",array0) # Mask한 배열 출력

array0:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1:
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
Mask100: 
 [[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]
