In [1]:
import numpy as np # numpy import 후 np로 약자 지정

생성한 배열의 최대값, 최소값, 합계, 평균값

In [6]:
array0 = np.arange(16).reshape(4, 4) # 0~15의 원소를 4x4배열로 생성
print("최대값:", np.max(array0))
print("최소값:", np.min(array0))
print("합계:", np.sum(array0))
print("평균값:", np.mean(array0))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


배열의 x축, y축 합계

In [7]:
array0 = np.arange(16).reshape(4, 4) # 0~15의 원소를 4x4배열로 생성
print(array0)
print("x축합계:", np.sum(array0, axis=0))
print("y축합계:", np.sum(array0, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
x축합계: [24 28 32 36]
y축합계: [ 6 22 38 54]
