4. 저장 및 불러오기

In [1]:
import numpy as np # numpy import 후 np로 약자 지정

배열의 저장 및 불러오기

In [2]:
array0 = np.arange(0, 10) # 0~9의 배열 생성
np.save('민머리.npy', array0) # array0를 민머리.npy로 저장
x = np.load('민머리.npy') # 민머리.npy를 불러옴
print(x) # 불러온 배열을 출력

[0 1 2 3 4 5 6 7 8 9]


다중배열의 저장 및 불러오기

In [3]:
array0 = np.arange(0, 10) # 0~9의 배열 생성
array1 = np.arange(10, 20) # 10~19의 배열 생성
np.savez('예함대.npz', array0=array0, array1=array1) # array0와 array1을 예함대.npz로 다중배열 저장
data = np.load('예함대.npz') # 예함대.npz를 불러옴
x = data['array0'] # 다중배열 중 array0
y = data['array1'] # 다중배열 중 array1
print(data) # 불러온 다중배열을 출력
print(x) # 다중배열 중 array0을 출력
print(y) # 다중배열 중 array1을 출력

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
