In [1]:
import numpy as np # numpy import 후 np로 약자 지정

배열의 오름차순

In [4]:
array0 = np.array([9, 2, 4, 1, 8]) # 9,2,4,1,8의 원소를 가진 배열 생성
array0.sort() # 배열을 오름차순
print(array0) # 오름차순한 배열을 출력

[1 2 4 8 9]


배열의 내림차순

In [5]:
array0 = np.array([9, 2, 4, 1, 8]) # 9,2,4,1,8의 원소를 가진 배열 생성
array0.sort() # 배열을 오름차순
print(array0[::-1]) # 오름차순한 배열을 반전하여 내림차순으로 출력

[9 8 4 2 1]


일정범위 데이터 생성

In [6]:
array0 = np.linspace(0, 9, 5) # 0부터9까지 5번의 동일한 간격으로 데이터 생성
print(array0) # 생성한 배열 출력

[0.   2.25 4.5  6.75 9.  ]


난수 생성

In [7]:
print(np.random.randint(0, 10, (2, 3))) # 0~9의 난수 원소를 갖는 2x3배열을 생성

[[9 7 5]
 [3 5 8]]


n번째의 난수 재연

In [8]:
np.random.seed(9999) # 9999번째의 난수 재연
print(np.random.randint(0, 10, (2, 3))) # 0~9의 9999번째의 난수 원소를 갖는 2x3배열을 생성

[[6 1 6]
 [5 5 9]]


배열의 복사

In [9]:
array0 = np.arange(0, 10) # 0~9의 원소를 가진 배열 생성
array1 = array0.copy() # 새로운 배열에 복사
print(array1) # 복사된 배열을 출력

[0 1 2 3 4 5 6 7 8 9]


배열의 중복된 원소 제거

In [10]:
array0 = np.array([1, 1, 2, 3, 3, 3, 1]) # 1,1,2,3,3,1의 원소를 가진 배열 생성
print(np.unique(array0)) # 중복된 원소를 제거하여 출력

[1 2 3]
