In [1]:
import numpy as np # numpy import 후 np로 약자 지정

0으로 초기화한 배열 생성

In [2]:
array0 = np.zeros((4, 4), dtype=float) # 0으로 초기화한 float타입의 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array0 size: 16
array0 dtype: float64


1으로 초기화한 배열 생성

In [3]:
array0 = np.ones((4, 4), dtype=float) # 1으로 초기화한 float타입의 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array0 size: 16
array0 dtype: float64
