In [1]:
import numpy as np # numpy import 후 np로 약자 지정

난수 배열 생성

In [5]:
array0 = np.random.randint(0, 15, (4, 4)) # 0~15의 난수값을 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[ 4  8 12  0]
 [12  7  1  7]
 [ 6  8  5 12]
 [13  0  7 10]]
array0 size: 16
array0 dtype: int32
