In [1]:
import numpy as np # numpy import 후 np로 약자 지정

표준정규분포를 갖는 배열 생성

In [6]:
array0 = np.random.normal (0, 1, (4, 4)) # 평균이 0, 표준편차가 1인 4x4배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array0 size:",array0.size) # 생성한 배열 사이즈 출력
print("array0 dtype:",array0.dtype) # 생성한 배열 데이터타입 출력

array0: 
 [[-0.83594591 -1.20188311 -1.05320855 -0.18966937]
 [ 1.20181632 -0.91580694  0.81518602  0.07167718]
 [-0.01931001  1.67890992  0.2378247  -1.30471993]
 [-0.70168283  0.60769567 -1.87763958 -0.51274564]]
array0 size: 16
array0 dtype: float64
