In [7]:
import numpy as np # numpy import 후 np로 약자 지정

배열 concatenate(합치기)

In [13]:
array0 = np.array([1, 2, 3]) # 1~3 배열 생성
array1 = np.array([4, 5, 6]) # 4~6 배열 생성
array2 = np.concatenate([array0, array1]) # array0과 array1을 합친 배열 생성
print("array0:", array0) # 생성한 배열 출력
print("array1:",array1) # 생성한 배열 출력
print("concatenate:",array2) # concatenate한 배열 출력

array0: [1 2 3]
array1: [4 5 6]
concatenate: [1 2 3 4 5 6]


In [17]:
array0 = np.arange(4).reshape(1, 4) # 0~3원소를 가지는 1x4배열 생성
array1 = np.arange(8).reshape(2, 4) # 0~7원소를 가지는 2x4배열 생성
array2 = np.concatenate([array0, array1], axis=0) # array0과 array1을 x축으로 합친 배열 생성
print("array0: \n", array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력
print("concatenate: \n",array2) # concatenate한 배열 출력

array0: 
 [[0 1 2 3]]
array1: 
 [[0 1 2 3]
 [4 5 6 7]]
concatenate: 
 [[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
