In [1]:
import numpy as np # numpy import 후 np로 약자 지정

배열을 split(분리)

In [12]:
array0 = np.arange(8).reshape(2, 4) # 0~7의 원소를 갖는 2x4배열 생성
left, right = np.split(array0, [2], axis=1) # y축의 2번째 원소를 기준으로 left, right split

print("array0: \n", array0)
print("left: \n", left)
print("left shape: \n", left.shape) # left의 형태
print("right: \n", right)
print("right shape: \n", right.shape) # right의 형태
print("right(0,1): \n",right[0][1]) # right의 (0, 1)원소 출력
print("right(1,1): \n",right[1][1]) # right의 (1, 1)원소 출력

array0: 
 [[0 1 2 3]
 [4 5 6 7]]
left: 
 [[0 1]
 [4 5]]
left shape: 
 (2, 2)
right: 
 [[2 3]
 [6 7]]
right shape: 
 (2, 2)
right(0,1): 
 3
right(1,1): 
 7
