In [2]:
import numpy as np # numpy import 후 np로 약자 지정

다른 차원의 덧셈 = 차원에 맞게 더해줌

In [3]:
array0 = np.arange(4).reshape(2, 2) # 0~3의 원소를 2x2배열로 생성
array1 = np.arange(2) # 0~1원소의 배열 생성
array2 = array0 + array1 # array0과 array1의 원소를 각각 더함
print("array0: \n",array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력
print("array0 + array1: \n",array2) # 배열의 덧셈

array0: 
 [[0 1]
 [2 3]]
array1: 
 [0 1]
array0 + array1: 
 [[0 2]
 [2 4]]


cocatenate(합치기)후 x축원소를 출력하여 더해줌

In [4]:
array0 = np.arange(0, 8).reshape(2, 4) # 0~7의 원소를 2x4배열로 생성
array1 = np.arange(0, 8).reshape(2, 4) # 0~7의 원소를 2x4배열로 생성
array2 = np.concatenate([array0, array1], axis=0) # array0과 array1을 x축으로 concatenate
array3 = np.arange(0, 4).reshape(4, 1) # 0~3의 원소를 4x1배열로 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력
print("array2: \n",array2) # concatenate한 배열 출력
print("array3: \n",array3) # 생성한 배열 출력
print("array2+3: \n",array2 + array3) # concatenate한 배열과 array3의 덧셈

array0: 
 [[0 1 2 3]
 [4 5 6 7]]
array1: 
 [[0 1 2 3]
 [4 5 6 7]]
array2: 
 [[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
array3: 
 [[0]
 [1]
 [2]
 [3]]
array2+3: 
 [[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]
