2. Numpy concatenate(합치기), split(분리)

In [1]:
import numpy as np # numpy import 후 np로 약자 지정

배열 concatenate(합치기)

In [2]:
array0 = np.array([1, 2, 3]) # 1~3 배열 생성
array1 = np.array([4, 5, 6]) # 4~6 배열 생성
array2 = np.concatenate([array0, array1]) # array0과 array1을 합친 배열 생성

print("array0:", array0) # 생성한 배열 출력
print("array1:",array1) # 생성한 배열 출력
print("concatenate:",array2) # concatenate한 배열 출력

array0: [1 2 3]
array1: [4 5 6]
concatenate: [1 2 3 4 5 6]


1차원 -> 2차원변경

In [3]:
array0 = np.array([1, 2, 3, 4]) # 1~4의 배열 생성
array1 = array0.reshape((2, 2)) # 2x2배열로 재배치
print("array0: \n",array0) # 생성한 배열 출력
print("reshape: \n",array1) # reshape한 배열 출력

array0: 
 [1 2 3 4]
reshape: 
 [[1 2]
 [3 4]]


x축을 기준으로 한 다차원 concatenate

In [4]:
array0 = np.arange(4).reshape(1, 4) # 0~4의 배열 생성 후 1x4배열로 재배치
array1 = np.arange(8).reshape(2, 4) # 0~8의 배열 생성 후 2x8배열로 재배치
array2 = np.concatenate([array0, array1], axis=0) # array0와 array1을 x축을 기준으로 합친 배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력
print("concatenate shape: \n",array2.shape) # concatenate한 배열의 형태 출력
print("concatenate: \n",array2) # concatenate한 배열 출력

array0: 
 [[0 1 2 3]]
array1: 
 [[0 1 2 3]
 [4 5 6 7]]
concatenate shape: 
 (3, 4)
concatenate: 
 [[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


y축을 기준으로한 다차원 split(분리)

In [5]:
array0 = np.arange(8).reshape(2, 4) # 0~8의 배열 생성 후 2x4배열로 재배치
left, right = np.split(array0, [2], axis=1) # array0을 y축을 기준으로 분리한 배열 생성
print("array0: \n",array0) # 생성한 배열 출력
print("left shape: \n",left.shape) # 분리한 left의 형태 출력
print("left: \n",left) # 분리한 left 배열 출력
print("rigth shape: \n",right.shape) # 분리한 right의 형태 출력
print("right: \n",right) # 분리한 right 배열 출력
print("right (0, 0): \n",right[0][0]) # right의 (0, 0) 원소 출력
print("right (1, 0): \n",right[1][0]) # right의 (1, 0) 원소 출력

array0: 
 [[0 1 2 3]
 [4 5 6 7]]
left shape: 
 (2, 2)
left: 
 [[0 1]
 [4 5]]
rigth shape: 
 (2, 2)
right: 
 [[2 3]
 [6 7]]
right (0, 0): 
 2
right (1, 0): 
 6
