3. Numpy 연산

In [1]:
import numpy as np # numpy import 후 np로 약자 지정

배열 곱셈 = 각 원소에 곱을 함

In [2]:
array0 = np.random.randint(1, 10, size=(2, 2)) # 1~10의 원소를 랜덤하게 2x2배열로 생성
array1 = array0 * 10 # 생성된 배열의 각 원소에 10을 곱함
print("array0: \n",array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력

array0: 
 [[6 9]
 [6 8]]
array1: 
 [[60 90]
 [60 80]]


다른 차원의 덧셈 = 차원에 맞게 더해줌

In [3]:
array0 = np.arange(4).reshape(2, 2) # 0~3의 원소를 2x2배열로 생성
array1 = np.arange(2) # 0~1원소의 배열 생성
array2 = array0 + array1 # array0과 array1의 원소를 각각 더함
print("array0: \n",array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력
print("array0 + array1: \n",array2) # 배열의 덧셈

array0: 
 [[0 1]
 [2 3]]
array1: 
 [0 1]
array0 + array1: 
 [[0 2]
 [2 4]]


cocatenate(합치기)후 x축원소를 출력하여 더해줌

In [4]:
array0 = np.arange(0, 8).reshape(2, 4) # 0~7의 원소를 2x4배열로 생성
array1 = np.arange(0, 8).reshape(2, 4) # 0~7의 원소를 2x4배열로 생성
array2 = np.concatenate([array0, array1], axis=0) # array0과 array1을 x축으로 concatenate
array3 = np.arange(0, 4).reshape(4, 1) # 0~3의 원소를 4x1배열로 생성
print("array0: \n",array0) # 생성한 배열 출력
print("array1: \n",array1) # 생성한 배열 출력
print("array2: \n",array2) # concatenate한 배열 출력
print("array3: \n",array3) # 생성한 배열 출력
print("array2+3: \n",array2 + array3) # concatenate한 배열과 array3의 덧셈

array0: 
 [[0 1 2 3]
 [4 5 6 7]]
array1: 
 [[0 1 2 3]
 [4 5 6 7]]
array2: 
 [[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
array3: 
 [[0]
 [1]
 [2]
 [3]]
array2+3: 
 [[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


0~15의 원소를 4x4배열로 생성 후 10미만의 원소를 100으로 mask

In [5]:
array0 = np.arange(16).reshape(4, 4) # 0~15의 원소를 4x4배열로 생성
print("array0:\n",array0) # 생성한 배열 출력

array1 = array0 < 10 # array0에서 10미만의 원소를 Mask
print("array1:\n",array1) # Mask한 배열 출력

array0[array1] = 100 # array1의 True값을 array0에 100으로 Mask
print("Mask100: \n",array0) # Mask한 배열 출력

array0:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1:
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
Mask100: 
 [[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


생성한 배열의 최대값, 최소값, 합계, 평균값

In [6]:
array0 = np.arange(16).reshape(4, 4) # 0~15의 원소를 4x4배열로 생성
print("최대값:", np.max(array0))
print("최소값:", np.min(array0))
print("합계:", np.sum(array0))
print("평균값:", np.mean(array0))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


배열의 x축, y축 합계

In [7]:
array0 = np.arange(16).reshape(4, 4) # 0~15의 원소를 4x4배열로 생성
print(array0)
print("x축합계:", np.sum(array0, axis=0))
print("y축합계:", np.sum(array0, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
x축합계: [24 28 32 36]
y축합계: [ 6 22 38 54]
