4. 저장 및 불러오기

In [1]:
import numpy as np # numpy import 후 np로 약자 지정

배열의 저장 및 불러오기

In [2]:
array0 = np.arange(0, 10) # 0~9의 배열 생성
np.save('민머리.npy', array0) # array0를 민머리.npy로 저장
x = np.load('민머리.npy') # 민머리.npy를 불러옴
print(x) # 불러온 배열을 출력

[0 1 2 3 4 5 6 7 8 9]


다중배열의 저장 및 불러오기

In [3]:
array0 = np.arange(0, 10) # 0~9의 배열 생성
array1 = np.arange(10, 20) # 10~19의 배열 생성
np.savez('예함대.npz', array0=array0, array1=array1) # array0와 array1을 예함대.npz로 다중배열 저장
data = np.load('예함대.npz') # 예함대.npz를 불러옴
x = data['array0'] # 다중배열 중 array0
y = data['array1'] # 다중배열 중 array1
print(data) # 불러온 다중배열을 출력
print(x) # 다중배열 중 array0을 출력
print(y) # 다중배열 중 array1을 출력

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


배열의 오름차순

In [4]:
array0 = np.array([9, 2, 4, 1, 8]) # 9,2,4,1,8의 원소를 가진 배열 생성
array0.sort() # 배열을 오름차순
print(array0) # 오름차순한 배열을 출력

[1 2 4 8 9]


배열의 내림차순

In [5]:
array0 = np.array([9, 2, 4, 1, 8]) # 9,2,4,1,8의 원소를 가진 배열 생성
array0.sort() # 배열을 오름차순
print(array0[::-1]) # 오름차순한 배열을 반전하여 내림차순으로 출력

[9 8 4 2 1]


일정범위 데이터 생성

In [6]:
array0 = np.linspace(0, 9, 5) # 0부터9까지 5번의 동일한 간격으로 데이터 생성
print(array0) # 생성한 배열 출력

[0.   2.25 4.5  6.75 9.  ]


난수 생성

In [7]:
print(np.random.randint(0, 10, (2, 3))) # 0~9의 난수 원소를 갖는 2x3배열을 생성

[[9 7 5]
 [3 5 8]]


n번째의 난수 재연

In [8]:
np.random.seed(9999) # 9999번째의 난수 재연
print(np.random.randint(0, 10, (2, 3))) # 0~9의 9999번째의 난수 원소를 갖는 2x3배열을 생성

[[6 1 6]
 [5 5 9]]


배열의 복사

In [9]:
array0 = np.arange(0, 10) # 0~9의 원소를 가진 배열 생성
array1 = array0.copy() # 새로운 배열에 복사
print(array1) # 복사된 배열을 출력

[0 1 2 3 4 5 6 7 8 9]


배열의 중복된 원소 제거

In [10]:
array0 = np.array([1, 1, 2, 3, 3, 3, 1]) # 1,1,2,3,3,1의 원소를 가진 배열 생성
print(np.unique(array0)) # 중복된 원소를 제거하여 출력

[1 2 3]
